name: Deploy to ConoHa VPS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: SSH and deploy
#       uses: appleboy/ssh-action@master
      env:
        HOST: ${{ secrets.CONOHA_VPS_PROD_IP }}
        USERNAME: ${{ secrets.CONOHA_VPS_PROD_USERNAME }}
        PRIVATE_KEY: ${{ secrets.CONOHA_VPS_PROD_KEY }}
        PORT: ${{ secrets.CONOHA_VPS_PROD_PORT }}
      run: |
        cd ~/itnav-hp
        git pull
        pnpm build
