name: Deploy to ConoHa VPS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CONOHA_VPS_PROD_IP }}
        username: ${{ secrets.CONOHA_VPS_PROD_USERNAME }}
        key: ${{ secrets.CONOHA_VPS_PROD_KEY }}
        port: ${{ secrets.CONOHA_VPS_PROD_PORT }}
        script: |
          echo $CONOHA_VPS_PROD_ID
          cd ~/itnav-hp
          git pull
          pnpm build
